export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_PENDING = "AUTH_USER_PENDING";
export const AUTH_USER_FAIL = "AUTH_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
